### ISSUE TITLE
Arduino Port Expander does not build on ESPHome 2025.2.0 - invalid new-expression of abstract class type

### ISSUE THREAD

**Issue by jezuk** [glmnet/esphome#5]
Hi,

I'm getting an error when building on ESPHome 2025.2.0, downgrading to 2024.12.4 fixes the issue.

```
src/main.cpp: In function 'void setup()':
src/main.cpp:360:111: error: invalid new-expression of abstract class type 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin'
   arduino_port_expander_arduinoportexpandergpiopin_id = new arduino_port_expander::ArduinoPortExpanderGPIOPin();
                                                                                                               ^
In file included from src/esphome.h:15,
                 from src/main.cpp:3:
src/esphome/components/arduino_port_expander/arduino_port_expander.h:56:7: note:   because the following virtual functions are pure within 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin':
 class ArduinoPortExpanderGPIOPin : public GPIOPin {
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/esphome/core/hal.h:4,
                 from src/esphome/core/application.h:7,
                 from src/esphome/components/api/api_connection.h:9,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/gpio.h:61:23: note: 	'virtual esphome::gpio::Flags esphome::GPIOPin::get_flags() const'
   virtual gpio::Flags get_flags() const = 0;
                       ^~~~~~~~~
```

Let me know if any more info/testing needed, thanks for any help!

YAML Snip:
```yaml
external_components:
  - source: github://glmnet/esphome@ape-external-component
    components: [arduino_port_expander]

arduino_port_expander:
  id: pro_mini08
  address: 0x08

switch:
  - platform: gpio
    pin:
      arduino_port_expander: pro_mini08
      number: 1
    id: relay_1
    name: Aux hose valve
```

Full clean build log:
```
INFO ESPHome 2025.2.0
INFO Reading configuration /config/esphome/esphome-web-1fcc68.yaml...
WARNING GPIO15 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO2 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO12 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-1fcc68-water-change-sys (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/AsyncTCP-esphome @ 2.1.4
INFO Installing esphome/AsyncTCP-esphome @ 2.1.4
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome@2.1.4 has been installed!
INFO AsyncTCP-esphome@2.1.4 has been installed!
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 3.2.2
INFO Installing esphome/ESPAsyncWebServer-esphome @ 3.2.2
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer-esphome@3.2.2 has been installed!
INFO ESPAsyncWebServer-esphome@3.2.2 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/noise-c @ 0.1.6
INFO Installing esphome/noise-c @ 0.1.6
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.6 has been installed!
INFO noise-c@0.1.6 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10018.4
INFO Installing esphome/libsodium @ 1.10018.4
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10018.4 has been installed!
INFO libsodium@1.10018.4 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Wire @ 2.0.0
|-- noise-c @ 0.1.6
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/arduino_port_expander/arduino_port_expander.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/dallas_temp/dallas_temp.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/esp32/core.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/esp32/gpio.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/esphome/ota/ota_esphome.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/gpio/one_wire/gpio_one_wire.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/gpio/switch/gpio_switch.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/i2c/i2c.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/i2c/i2c_bus_arduino.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/i2c/i2c_bus_esp_idf.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/ina3221/ina3221.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/ledc/ledc_output.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/logger/logger_esp32.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/logger/logger_esp8266.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/logger/logger_host.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/logger/logger_libretiny.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/logger/logger_rp2040.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/one_wire/one_wire.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/one_wire/one_wire_bus.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/ota/ota_backend.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/ota/ota_backend_arduino_libretiny.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/output/automation.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/output/float_output.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/rtttl/rtttl.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/safe_mode/safe_mode.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/sensor/sensor.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/socket/lwip_sockets_impl.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/switch/automation.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/switch/switch.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/wifi/wifi_component_libretiny.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/application.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/color.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/component.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/component_iterator.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/controller.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/entity_base.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/helpers.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/log.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/ring_buffer.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/scheduler.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/string_ref.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/time.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/esphome/core/util.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/src/main.cpp.o
Building .pioenvs/esphome-1fcc68-water-change-sys/bootloader.bin
Generating partitions .pioenvs/esphome-1fcc68-water-change-sys/partitions.bin
Creating esp32 image...
Successfully created esp32 image.
Compiling .pioenvs/esphome-1fcc68-water-change-sys/lib1b6/AsyncTCP-esphome/AsyncTCP.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/lib64d/WiFi/WiFi.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/lib64d/WiFi/WiFiAP.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:360:111: error: invalid new-expression of abstract class type 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin'
   arduino_port_expander_arduinoportexpandergpiopin_id = new arduino_port_expander::ArduinoPortExpanderGPIOPin();
                                                                                                               ^
In file included from src/esphome.h:15,
                 from src/main.cpp:3:
src/esphome/components/arduino_port_expander/arduino_port_expander.h:56:7: note:   because the following virtual functions are pure within 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin':
 class ArduinoPortExpanderGPIOPin : public GPIOPin {
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/esphome/core/hal.h:4,
                 from src/esphome/core/application.h:7,
                 from src/esphome/components/api/api_connection.h:9,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/gpio.h:61:23: note: 	'virtual esphome::gpio::Flags esphome::GPIOPin::get_flags() const'
   virtual gpio::Flags get_flags() const = 0;
                       ^~~~~~~~~
src/main.cpp:390:113: error: invalid new-expression of abstract class type 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin'
   arduino_port_expander_arduinoportexpandergpiopin_id_2 = new arduino_port_expander::ArduinoPortExpanderGPIOPin();
                                                                                                                 ^
src/main.cpp:420:113: error: invalid new-expression of abstract class type 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin'
   arduino_port_expander_arduinoportexpandergpiopin_id_3 = new arduino_port_expander::ArduinoPortExpanderGPIOPin();
                                                                                                                 ^
src/main.cpp:450:113: error: invalid new-expression of abstract class type 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin'
   arduino_port_expander_arduinoportexpandergpiopin_id_4 = new arduino_port_expander::ArduinoPortExpanderGPIOPin();
                                                                                                                 ^
src/main.cpp:480:113: error: invalid new-expression of abstract class type 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin'
   arduino_port_expander_arduinoportexpandergpiopin_id_5 = new arduino_port_expander::ArduinoPortExpanderGPIOPin();
                                                                                                                 ^
src/main.cpp:510:113: error: invalid new-expression of abstract class type 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin'
   arduino_port_expander_arduinoportexpandergpiopin_id_6 = new arduino_port_expander::ArduinoPortExpanderGPIOPin();
                                                                                                                 ^
src/main.cpp:540:113: error: invalid new-expression of abstract class type 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin'
   arduino_port_expander_arduinoportexpandergpiopin_id_7 = new arduino_port_expander::ArduinoPortExpanderGPIOPin();
                                                                                                                 ^
src/main.cpp:570:113: error: invalid new-expression of abstract class type 'esphome::arduino_port_expander::ArduinoPortExpanderGPIOPin'
   arduino_port_expander_arduinoportexpandergpiopin_id_8 = new arduino_port_expander::ArduinoPortExpanderGPIOPin();
                                                                                                                 ^
Compiling .pioenvs/esphome-1fcc68-water-change-sys/lib64d/WiFi/WiFiClient.cpp.o
Compiling .pioenvs/esphome-1fcc68-water-change-sys/lib64d/WiFi/WiFiGeneric.cpp.o
*** [.pioenvs/esphome-1fcc68-water-change-sys/src/main.cpp.o] Error 1
========================= [FAILED] Took 65.48 seconds =========================
```

**Comment by glmnet** [comment]
i guess this was fixed. Otherwise please reopen
